# Modifiez ce document pour modifier le site du sommet

# titre du site
title: >
  Terre des jeunes

# description tel qu'il apparaît sur Google
description: >
  Terre des jeunes organise un premier sommet international qui rassemble des jeunes bénévoles d'à travers le monde qui oeuvrent pour l'environnement.

# slogan ligne 1 (taille moyenne)
slogan_ligne_1: >
  Août 2015

# slogan ligne 2 (gros texte)
slogan_ligne_2: >
  Sommet international au Togo

# slogan ligne 3 en plus petit
slogan_ligne_3: >
  Terre des jeunes organise un premier sommet international qui rassemble des bénévoles d'à travers le monde qui oeuvrent pour l'environnement.

# grosse image en haut de la page
grosse_image:
  # http://terredesjeunes.org/sites/terredesjeunes.org/files/js.JPG
  # http://terredesjeunes.org/sites/terredesjeunes.org/files/Corbis-42-21178497.jpg
  http://terredesjeunes.org/sites/terredesjeunes.org/files/imagecache/images_sur_nodes/4189857.png

# latitude et longitude du site
emplacement_ll:
  6.428705,1.2117147

emplacement_zoom:
  9

# titre de la première section
section_1_titre:
  À propos du  sommet

# titre de la première section
section_1_menu:
  À propos

# description de la première section
section_1_desc: >
  Organisé par le réseau <a href="http://terredesjeunes.org">Terre des jeunes</a>, actif depuis 1985, il s'agit d'une première grande rencontre internationale. 
  Le but est de stimuler le bénévolat, l'action directe, les connaissances pratiques en matière de reboisement et d'organisation communautaire.
  Nous voulons travailler aussi à trouver des modes de fonctionnement super simples, décentralisés et écologiques.<br/>
  Au menu : du bénévolat, des rencontres et discussions, de l'action directe, des échanges culturels, de la fête. Un volet touristique et culturel est prévu à la suite du Sommet. 
  <a href="http://sommet.terredesjeunes.org/comite-organisation.html">Voyez la composition de notre comité d'organisation</a>, <a href="http://terredesjeunes.org/contact?edit[cid]=4">Contactez les organisateurs au Togo</a> ou <a href="http://terredesjeunes.org/contact">Terre des jeunes transnational au Québec (Canada)</a> pour plus d'infos.

section_1_colonne_1_titre:
  Rencontres

section_1_colonne_1_desc:
  Des représentants des antennes de Terre des jeunes de plusieurs pays de la Francophonie seront présents, dont le Togo, la Côte d'Ivoire, Haïti, le Canada, le Bénin, etc. Ainsi que toute personne intéressée à changer le monde est invitée à contribuer avec sa culture et ses idées.

section_1_colonne_2_titre:
  Échanges d'idées

section_1_colonne_2_desc: >
  Nous voulons ouvrir le débat sur :
  <ul>
  <li>Comment financer des activités sans devenir prisonniers du cycle des subventions?</li>
  <li>Comment gérer un organisme de manière décentralisée et ouverte?</li>
  <li>Comment vivre et agir de manière écologique? Quels sont les modèles inspirés du Sud?</li>
  </ul>
  <p>Voici les grandes thématiques du Sommet :</p>
  <ul>
  <li>L'implication environnementale par des actions concrètes</li>
  <li>Le fonctionnement et le financement des organismes autogérés, le modèle Terre des jeunes</li>
  <li>L'influence de nos pratiques culturelles et notre mode de vie sur notre environnement</li>
  </ul>

section_1_colonne_3_titre:
  Ateliers pratiques

section_1_colonne_3_desc: >
  <p>Nous avons prévu des chantiers pratiques chaque jour. <a href="/ateliers">Voyez la liste des ateliers ici.</a></p>
  <ul>
   <li>Plantation d'arbres et reboisement : Graine de vie, Sylvelle, Fête de l'arbre, parc sylva. Essences intéressantes.</li>
   <li>Préparation d'un jardin communautaire et/ou collectif : Choix du modèle, enrichir la terre (compost), plantes locales.</li>
   <li>Construction d'un habitat : Choix de l'habitat, de la structure, de la couverture et techniques. Contribution au village écologique.</li>
   <li>Autres chantiers à déterminer.</li>
  <p>Des conférences axées sur la pratique sont aussi prévues.</p>

section_2_titre: Où, quand, combien?

section_2_menu: Où, quand, combien?

section_2_texte: >
  Pour tout savoir sur le projet du sommet, voir notre <strong>document de présentation</strong> en <a href="http://terredesjeunes.org/sites/terredesjeunes.org/files/issues/sommet_tdj_togo_2015_v131202FR.pdf">français</a>,
  <a href="http://terredesjeunes.org/sites/terredesjeunes.org/files/issues/sommet_tdj_togo_2015_v130220EN.pdf">anglais</a> ou <a href="http://terredesjeunes.org/sites/terredesjeunes.org/files/issues/_sommet_tdj_togo_2015_v130220ES.pdf">espagnol</a>.
  
section_2_dates:
  Août 2015

section_2_dates_desc:
  

section_2_image:
  image de ...

section_2_colonne_1_titre:
  Où?

section_2_colonne_1_desc:
  À 30 minutes de Lomé, capitale du Togo, dans le village <a href="http://sommet.terredesjeunes.org/#carte">Tséviépé</a>.

section_2_colonne_1_image:
  http://terredesjeunes.org/sites/terredesjeunes.org/files/terre.png

section_2_colonne_2_titre:
  Quand?

section_2_colonne_2_desc:
  7 au 13 août - Rencontres préparatoires de TDJ <br/>
  14 au 18 août - Sommet ouvert à tous <br/>
  20 au 25 août - volet culturel et touristique <br/>
  Voir notre <a href="horaire.html">horaire prévu</a>

section_2_colonne_2_image:
  http://terredesjeunes.org/sites/terredesjeunes.org/files/clock50px.png

section_2_colonne_3_titre:
  Combien?

section_2_colonne_3_desc:
  Pour connaître les frais et vous inscrire au Sommet,
  visitez notre <a href="/inscription/">page d'inscription</a>

section_2_colonne_3_image:
  http://terredesjeunes.org/sites/terredesjeunes.org/files/combien.png

section_3_titre:
  Activités prévues

section_3_menu:
  Activités

section_3_desc:
  Activités pratiques et culturelles

section_3_desc_long: >
  Veuillez consulter notre <a href="horaire.html">horaire</a>.
  Vous pouvez aussi <a href="https://github.com/alberto56/minisite-sommet-tdj/edit/gh-pages/_data/activites.yml">modifier les textes ci-dessous</a>
  (avec votre compte <a href="https://github.com/">GitHub</a>).

section_4_titre:
  Infos pratiques

section_4_menu:
  Infos pratiques

# SVP ne modifiez pas ce qui se trouve sous cette ligne
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sommet.terredesjeunes.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
